apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: solutions/helm/nginx-deployment 
    repoURL: https://github.com/oleksandrsirenko/cloud-native-foundations 
    targetRevision: HEAD
